services:
  postgres:
    image: postgres:15.1-alpine3.17
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: hotel
      TZ: UTC
    healthcheck:
      test: pg_isready -U postgres -d hotel
      interval: 30s
      timeout: 15s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 10
        window: 120s
      resources:
        limits:
          memory: 1GB
          cpus: '1'
        reservations:
          memory: 50MB
          cpus: '0.10'
    logging:
      driver: json-file
      options:
        max-size: 10M
        max-file: 3